# Generated by Django 4.1 on 2022-09-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=12)),
                ('store_class', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('country_code', models.CharField(max_length=15)),
                ('longitude', models.FloatField(max_length=12)),
                ('latitude', models.FloatField(max_length=12)),
                ('mon_open_hours', models.CharField(max_length=15)),
                ('tue_open_hours', models.CharField(max_length=15)),
                ('wed_open_hours', models.CharField(max_length=15)),
                ('thu_open_hours', models.CharField(max_length=15)),
                ('fri_open_hours', models.CharField(max_length=15)),
                ('sat_open_hours', models.CharField(max_length=15)),
                ('sun_open_hours', models.CharField(max_length=15)),
                ('streetName1', models.CharField(max_length=25)),
                ('streetName2', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=15)),
                ('address_string', models.CharField(max_length=35)),
            ],
        ),
    ]
