# Generated by Django 4.1 on 2022-09-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0002_alter_store_address_string_alter_store_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
