# Generated by Django 4.1 on 2022-09-10 19:36

from django.db import migrations, models
import storesinfo.shared


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0003_remove_store_id_alter_store_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.CharField(default=storesinfo.shared.generateID, max_length=6, primary_key=True, serialize=False),
        ),
    ]
