# Generated by Django 4.1 on 2022-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0006_alter_kmeans_clustersnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeans',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
