# Generated by Django 4.1 on 2022-10-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0007_kmeans_name_population_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmeans',
            old_name='name',
            new_name='titleCluster',
        ),
        migrations.RenameField(
            model_name='population',
            old_name='name',
            new_name='titleSet',
        ),
    ]
