# Generated by Django 4.1 on 2022-10-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0008_rename_name_kmeans_titlecluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='latitudeRange',
        ),
        migrations.RemoveField(
            model_name='population',
            name='longitudeRange',
        ),
        migrations.AddField(
            model_name='population',
            name='latitudeRangeMax',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='latitudeRangeMin',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='longitudeRangeMax',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='longitudeRangeMin',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
