# Generated by Django 4.1 on 2022-10-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0009_remove_population_latituderange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='clusterStd',
        ),
        migrations.RemoveField(
            model_name='population',
            name='latitudeRangeMax',
        ),
        migrations.RemoveField(
            model_name='population',
            name='latitudeRangeMin',
        ),
        migrations.RemoveField(
            model_name='population',
            name='longitudeRangeMax',
        ),
        migrations.RemoveField(
            model_name='population',
            name='longitudeRangeMin',
        ),
        migrations.RemoveField(
            model_name='population',
            name='samplesNumber',
        ),
        migrations.AddField(
            model_name='population',
            name='latitudes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='longitudes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
