# Generated by Django 4.1 on 2022-10-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesinfo', '0010_remove_population_clusterstd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmeans',
            name='clusterStd',
        ),
    ]
